[package]
name = "tak-persistence-sea-orm-entites"
version = "0.1.0"
edition = "2024"

[dependencies]
chrono = "0.4.42"
sea-orm = { version = "2.0.0-rc", features = [
    "sqlx-mysql",
    "runtime-tokio-native-tls",
    "macros",
] }
serde_json = "1.0.143"
