[package]
name = "tak-server"
version = "0.1.0"
edition = "2024"
default-run = "tak-server"

[workspace]
resolver = "3"
members = [
    "api/tak-server-api",
    "api/tak-server-http-api",
    "domain/tak-core",
    "tak-server-app",
    "domain/tak-server-domain",
    "more-dashmap",
    "persistence/tak-events-persistence",
    "persistence/tak-persistence-sea-orm",
    "tak-client", "infra/tak-email-lettre", "infra/tak-events-google-sheets",
]

[dependencies]
dotenvy = "0.15.7"
log = "0.4.28"
log4rs = { version = "1.4.0", features = ["gzip"] }
tak-events-persistence = { path = "./persistence/tak-events-persistence" }
tak-persistence-sea-orm = { path = "./persistence/tak-persistence-sea-orm" }
tak-server-api = { path = "./api/tak-server-api" }
tak-server-domain = { path = "./domain/tak-server-domain" }
tak-server-http-api = { path = "./api/tak-server-http-api" }
tokio = { version = "1.47.1", features = ["full"] }
