[package]
name = "tak-server"
version = "0.1.0"
edition = "2024"
default-run = "tak-server"

[workspace]
resolver = "3"
members = [
    "tak-client",
    "tak-core",
    "tak-persistence-sea-orm",
    "tak-server-domain",
    "tak-server-api",
    "tak-server-http-api",
]

[dependencies]

dotenvy = "0.15.7"
tokio = { version = "1.47.1", features = ["full"] }
tak-server-domain = { path = "./tak-server-domain" }
tak-persistence-sea-orm = { path = "./tak-persistence-sea-orm" }
tak-server-api = { path = "./tak-server-api" }
tak-server-http-api = { path = "./tak-server-http-api" }
log = "0.4.28"
log4rs = { version = "1.4.0", features = ["gzip"] }
