dsn: ${DSN}
version: v1.3.0
serve:
  public:
    host: 0.0.0.0
    port: 4433
    base_url: set_by_env_variable

  admin:
    host: 0.0.0.0
    port: 4434
    base_url: set_by_env_variable

selfservice:
  default_browser_return_url: set_by_env_variable

  methods:
    password:
      enabled: true

  flows:
    login:
      ui_url: set_by_env_variable
    registration:
      enabled: true
      ui_url: set_by_env_variable
      after:
        password:
          hooks:
            - hook: show_verification_ui
    settings:
      ui_url: set_by_env_variable
    recovery:
      enabled: true
      ui_url: set_by_env_variable
    verification:
      enabled: true
      ui_url: set_by_env_variable

log:
  level: debug
  format: json

identity:
  default_schema_id: default
  schemas:
    - id: default
      url: file:///etc/config/kratos/user.schema.json

    - id: bot
      url: file:///etc/config/kratos/bot.schema.json

courier:
  smtp:
    connection_uri: smtp://set_by_env_variable
